from setuptools import setup, find_packages

setup(
    name='django-phatpages',
    version='4.0.0',
    description='A reusable Django application for simple static pages.',
    long_description=open('README.rst').read(),
    long_description_content_type='text/x-rst',
    author='The Atlantic',
    author_email='programmers@theatlantic.com',
    url='https://github.com/theatlantic/django-phatpages',
    download_url='https://github.com/theatlantic/django-phatpages/tarball/master',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    install_requires=['Django>=2.2'],
    python_requires='>=3.6,<4',
    zip_safe=False,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Topic :: Software Development',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.0',
        'Framework :: Django :: 3.1',
        'Framework :: Django :: 3.2',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
)
